# Generated by Django 3.2.6 on 2021-08-09 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
