# Generated by Django 3.2.6 on 2021-08-12 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967)),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='lv1_approval_action_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967)),
        ),
        migrations.AddField(
            model_name='post',
            name='lv1_approval_status',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='lv2_approval_action_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967)),
        ),
        migrations.AddField(
            model_name='post',
            name='lv2_approval_status',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='lv3_approval_action_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967)),
        ),
        migrations.AddField(
            model_name='post',
            name='lv3_approval_status',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='oa_status',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='oa_success_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967)),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967)),
        ),
        migrations.AddField(
            model_name='post',
            name='send_submit_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967)),
        ),
        migrations.AddField(
            model_name='post',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967)),
        ),
        migrations.AddField(
            model_name='post',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 12, 9, 28, 3, 282967), null=True),
        ),
    ]
