# Generated by Django 3.2.6 on 2021-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='chinese_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
