# Generated by Django 3.2.6 on 2021-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_chinese_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststatus',
            name='chinese_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
