# Generated by Django 3.2.6 on 2021-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='旅游', max_length=255, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='保存'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_submit',
            field=models.BooleanField(default=False, verbose_name='提交'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(default='大数据组', max_length=255, verbose_name='组别'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='title tag', max_length=255, verbose_name='标签'),
        ),
    ]
