# Generated by Django 3.2.6 on 2021-08-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210817_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_submit',
            field=models.BooleanField(default=False, verbose_name='直接提交'),
        ),
    ]
