# Generated by Django 3.2.6 on 2021-08-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_is_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
