# Generated by Django 3.2.6 on 2021-08-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(upload_to='', verbose_name='上传文件'),
        ),
    ]
