# Generated by Django 3.2.6 on 2021-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
