# Generated by Django 3.2.6 on 2021-08-20 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210819_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_visiter',
            new_name='is_visitor',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('1', 'publisher'), ('2', 'approver'), ('3', 'visitor')], default='3', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
