# Generated by Django 3.2.6 on 2021-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210820_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('1', 'publisher'), ('2', 'approver'), ('3', 'visitor'), ('4', 'admin'), ('5', 'dev')], default='3', max_length=25),
        ),
    ]
