# Generated by Django 3.2.6 on 2021-08-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_post_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.CharField(choices=[('1', 'origin'), ('2', 'reproduction')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(upload_to='media\\uploadPosts/2021/8/', verbose_name='上传文件'),
        ),
    ]
