# Generated by Django 3.2.6 on 2021-09-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210831_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_lv4_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(upload_to='media\\uploadPosts/2021/9/', verbose_name='上传文件'),
        ),
    ]
