# Generated by Django 3.2.6 on 2021-09-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20210908_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lv4_approval_action_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lv4_approval_status',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='lv4_approver',
            field=models.IntegerField(default=-1),
        ),
    ]
