# Generated by Django 3.2.6 on 2021-09-09 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20210909_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_article_link',
            field=models.CharField(blank=True, help_text='集团文章link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='实例创建时间戳', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='快捷状态判断，用于复杂SQL限定之先决条件，True: 草稿未提交，False:内部提交，等待内部审批', verbose_name='保存'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_submit',
            field=models.BooleanField(default=False, help_text='快捷状态判断，直接提交状态标签', verbose_name='直接提交'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv2_approval_action_datetime',
            field=models.DateTimeField(blank=True, help_text='审批通过节点的时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv2_approval_status',
            field=models.CharField(default='0', help_text='0:未提交， 1：已提交未审批，2:已提交已审批通过，3:已提交已驳回', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv2_approver',
            field=models.IntegerField(default=-1, help_text='审批人ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv3_approval_action_datetime',
            field=models.DateTimeField(blank=True, help_text='审批通过节点的时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv3_approval_status',
            field=models.CharField(default='0', help_text='0:未提交， 1：已提交未审批，2:已提交已审批通过，3:已提交已驳回', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv3_approver',
            field=models.IntegerField(default=-1, help_text='审批人ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv4_approval_action_datetime',
            field=models.DateTimeField(blank=True, help_text='审批通过节点的时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv4_approval_status',
            field=models.CharField(default='0', help_text='0:未进入报送审批， 1：已提交未审批，2:已提交已审批通过，3:已提交已驳回', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='lv4_approver',
            field=models.IntegerField(default=-1, help_text='审批人ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='oa_status',
            field=models.CharField(default='0', help_text='报送状态，0 未报送（内部审批未完成时为该状态） 1（报送审批中，副院长审批）2（审批通过）3（审批驳回）', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='oa_success_time',
            field=models.DateTimeField(blank=True, help_text='集团获取文章并发布时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False, help_text='状态标签，True:内部发布等待报送审批，False：内部审批中'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='内部发布时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='send_submit_time',
            field=models.DateTimeField(blank=True, help_text='集团发起get请求时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间戳'),
        ),
    ]
