# Generated by Django 3.2.6 on 2021-09-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20210909_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='oa_status',
            field=models.CharField(default='0', help_text='报送状态，0 未报送（内部审批未完成时为该状态） 1（报送审批中，副院长审批）2（审批通过,报送中）3（审批驳回,未报送）4：集团已接收通过 5.集团已发布', max_length=5),
        ),
    ]
