# Generated by Django 3.2.6 on 2021-09-28 18:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_post_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(upload_to=blog.models.get_absolute_upload_path, verbose_name='上传文件'),
        ),
    ]
