# Generated by Django 3.2.6 on 2022-02-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_alter_post_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='oa_status',
            field=models.CharField(default='0', help_text='报送状态，0 未报送（内部审批未完成时为该状态） 1报送成功', max_length=5),
        ),
    ]
