# Generated by Django 3.2.6 on 2021-09-28 18:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_app_name', models.CharField(max_length=255)),
                ('attachment_app_model', models.CharField(max_length=255)),
                ('attachment_id', models.CharField(help_text='APPs model primary key for attachment', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_order_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='create an uuid for each order', primary_key=True, serialize=False)),
                ('process_description', models.TextField(verbose_name='流程描述')),
                ('process_name', models.CharField(max_length=255, verbose_name='流程名称')),
                ('process_pattern', models.CharField(max_length=255, verbose_name='流程模板')),
                ('process_type', models.CharField(max_length=255, verbose_name='流程类型')),
                ('process_init_time', models.DateTimeField(auto_now_add=True)),
                ('process_update_time', models.DateTimeField(auto_now=True)),
                ('process_start_time', models.DateTimeField(default=datetime.datetime(2021, 9, 28, 18, 38, 46, 247818))),
                ('process_duration', models.DurationField(help_text='流程持续天数', null=True, verbose_name='持续时长')),
                ('process_end_date', models.DateTimeField(blank=True, null=True)),
                ('process_sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='create an uuid for each move', primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=255, verbose_name='动作类型')),
                ('task_seq', models.IntegerField(default=0, verbose_name='动作顺序')),
                ('task_status', models.CharField(max_length=255, verbose_name='执行状态')),
                ('task_state', models.CharField(max_length=255, verbose_name='动作状态')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.process')),
                ('task_sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_seq', models.IntegerField(default=0, verbose_name='步骤顺序')),
                ('step_condition_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='前置要求')),
                ('step_condition', models.JSONField(verbose_name='前置要求')),
                ('step_owner', models.CharField(max_length=255, verbose_name='执行人')),
                ('step_assigner', models.CharField(blank=True, max_length=255, null=True, verbose_name='转发发出人')),
                ('step_assignee', models.CharField(blank=True, max_length=255, null=True, verbose_name='转出给')),
                ('step_create_time', models.DateTimeField(auto_now_add=True)),
                ('step_update_time', models.DateTimeField(auto_now=True)),
                ('step_start_time', models.DateTimeField(blank=True, null=True)),
                ('step_duration', models.DurationField(default=datetime.timedelta(0))),
                ('step_end_time', models.DateTimeField(blank=True, null=True)),
                ('step_status', models.CharField(max_length=255, verbose_name='执行状态')),
                ('step_state', models.CharField(max_length=255, verbose_name='步骤状态')),
                ('step_type', models.CharField(max_length=255, verbose_name='步骤类型')),
                ('step_attachment_snapshot', models.JSONField()),
                ('step_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.attachment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.task')),
            ],
        ),
    ]
