# Generated by Django 3.2.6 on 2021-09-29 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0002_alter_process_process_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 9, 30, 12, 283201)),
        ),
    ]
