# Generated by Django 3.2.6 on 2021-12-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0004_alter_process_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={},
        ),
    ]
