# Generated by Django 3.2.6 on 2021-09-29 10:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0005_auto_20210929_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='id',
        ),
        migrations.AddField(
            model_name='step',
            name='step_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='create an uuid for each STEP', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 28, 19, 573623)),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 28, 19, 574589)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='create an uuid for each Task', primary_key=True, serialize=False),
        ),
    ]
