# Generated by Django 3.2.6 on 2021-12-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0005_alter_projectrequirement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={'permissions': (('patch_projectrequirement', 'can patch project requirement'),)},
        ),
    ]
