# Generated by Django 3.2.6 on 2021-12-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0006_auto_20211203_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'permissions': (('packup_process', '合并流程'), ('dispatch_process', '分发流程'))},
        ),
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={'permissions': (('patch_projectrequirement', '分发'),)},
        ),
    ]
