# Generated by Django 3.2.6 on 2021-09-29 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0006_auto_20210929_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attachment_id',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_identify',
            field=models.CharField(default='', help_text='APPs model primary key for attachment', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 11, 9, 4, 523254)),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 11, 9, 4, 524219)),
        ),
    ]
