# Generated by Django 3.2.6 on 2021-09-29 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0007_auto_20210929_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_attachment',
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 11, 12, 12, 892742)),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 11, 12, 12, 892742)),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
