# Generated by Django 3.2.6 on 2021-12-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0008_alter_projectrequirement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={'permissions': (('patch_projectrequirement', '分发'), ('view_projectrequirement_submitted', '查看课题需求'), ('view_projectrequirement_set_to_annual', '查看年度课题需求'))},
        ),
    ]
