# Generated by Django 3.2.6 on 2021-09-29 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0009_auto_20210929_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_attachment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.attachment'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 11, 20, 19, 42542)),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 11, 20, 19, 42542)),
        ),
    ]
