# Generated by Django 3.2.6 on 2021-12-15 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0010_auto_20211213_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
