# Generated by Django 3.2.6 on 2021-10-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0011_auto_20210929_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
