# Generated by Django 3.2.6 on 2021-12-15 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0012_message_messagehandler_messagepattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
