# Generated by Django 3.2.6 on 2021-10-11 15:30

import ApprovalSystemOCT.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0012_book_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_attachment_snapshot',
            field=models.JSONField(blank=True, default=ApprovalSystemOCT.models.snapshot_default),
        ),
    ]
