# Generated by Django 3.2.6 on 2021-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0013_message_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_state',
            field=models.CharField(default='0', max_length=25, verbose_name='执行情况'),
        ),
    ]
