# Generated by Django 3.2.6 on 2021-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0013_alter_step_step_attachment_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='研究项目')),
                ('project_type', models.CharField(default='0', help_text='0.未选择,1.创新前瞻性研究；2.产品标准化研究，3.产品创新研究', max_length=25, verbose_name='课题类型')),
                ('project_research_direction', models.CharField(default='0', help_text='0.未选择,1.新型城镇化；2.文化&品牌；3.主题公园&新场景；4.新商业；5.产品管理；6.旅游大数据；7.康旅；8.创新投；9.其他', max_length=25, verbose_name='研究方向')),
                ('project_department', models.CharField(default='', max_length=255, verbose_name='需求单位')),
                ('project_department_sponsor', models.CharField(default='', max_length=25, verbose_name='需求单位联系人')),
                ('project_department_phone', models.CharField(default='', max_length=50, verbose_name='联系电话')),
                ('project_co_group', models.TextField(default='', verbose_name='联合工作小组成员及分工')),
                ('project_research_funding', models.CharField(default='', max_length=255, verbose_name='研究经费')),
                ('project_outsourcing_funding', models.CharField(default='', max_length=255, verbose_name='外协预算')),
                ('project_start_time', models.DateTimeField(null=True, verbose_name='研究实施计划时间（起）')),
                ('project_end_time', models.DateTimeField(null=True, verbose_name='研究实施计划时间（止）')),
                ('project_detail', models.TextField(default='', verbose_name='具体分项任务内容及安排')),
                ('project_purpose', models.TextField(default='', verbose_name='主要创新研究课题内容、目标及意义')),
                ('project_preparation', models.TextField(default='', verbose_name='与课题相关的前期工作情况，现有基础条件')),
                ('project_difficult', models.TextField(default='', verbose_name='研究课题的重点及难点')),
            ],
        ),
    ]
