# Generated by Django 3.2.6 on 2021-12-17 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0015_alter_step_step_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='next',
            field=models.JSONField(default=dict, null=True, verbose_name='后继'),
        ),
        migrations.AlterField(
            model_name='process',
            name='prev',
            field=models.JSONField(default=dict, null=True, verbose_name='前序'),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_co_worker',
            field=models.ManyToManyField(blank=True, related_name='process_co_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_status',
            field=models.CharField(default='1', max_length=255, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_co_worker',
            field=models.ManyToManyField(blank=True, related_name='co_worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
