# Generated by Django 3.2.6 on 2021-10-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0015_auto_20211013_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='process_sponsor',
            new_name='process_executor',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_description',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_duration',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_end_date',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_init_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_name',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_start_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_type',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_update_time',
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255, verbose_name='流程名称')),
                ('process_pattern', models.CharField(max_length=255, verbose_name='流程模板')),
                ('process_type', models.CharField(max_length=255, verbose_name='流程类型')),
                ('process_init_time', models.DateTimeField(auto_now_add=True)),
                ('process_update_time', models.DateTimeField(auto_now=True)),
                ('process_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('process_duration', models.DurationField(help_text='流程持续天数', null=True, verbose_name='持续时长')),
                ('process_end_date', models.DateTimeField(blank=True, null=True)),
                ('process_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('process_executor', models.ManyToManyField(related_name='executors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='process',
            name='process_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.processtype'),
        ),
    ]
