# Generated by Django 3.2.6 on 2021-10-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0016_auto_20211014_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='process_pattern',
        ),
    ]
