# Generated by Django 3.2.6 on 2021-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0016_auto_20211217_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='next',
            field=models.JSONField(blank=True, default=dict, verbose_name='后继'),
        ),
        migrations.AlterField(
            model_name='process',
            name='prev',
            field=models.JSONField(blank=True, default=dict, verbose_name='前序'),
        ),
    ]
