# Generated by Django 3.2.6 on 2021-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0017_auto_20211217_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='conjunction',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='关联'),
        ),
        migrations.AlterField(
            model_name='process',
            name='next',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='后继'),
        ),
        migrations.AlterField(
            model_name='process',
            name='prev',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='前序'),
        ),
    ]
