# Generated by Django 3.2.6 on 2021-10-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0017_remove_process_process_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.processtype'),
            preserve_default=False,
        ),
    ]
