# Generated by Django 3.2.6 on 2021-12-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0018_auto_20211217_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'permissions': (('packup_process', '合并流程'), ('dispatch_process', '分发流程'), ('approval_process', '审批权限'))},
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
