# Generated by Django 3.2.6 on 2021-10-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0018_process_process_pattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processtype',
            old_name='process_end_date',
            new_name='process_end_time',
        ),
    ]
