# Generated by Django 3.2.6 on 2021-10-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0019_rename_process_end_date_processtype_process_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype',
            name='process_pattern',
        ),
    ]
