# Generated by Django 3.2.6 on 2021-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0020_remove_processtype_process_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_publish_book', '发布图书'), ('can_repeal', '撤销发布'))},
        ),
        migrations.AlterField(
            model_name='processtype',
            name='process_type',
            field=models.CharField(choices=[('0', '未选择'), ('1', '创新前瞻性研究'), ('2', '产品标准化研究'), ('3', '产品创新研究')], max_length=255, verbose_name='流程类型'),
        ),
    ]
