# Generated by Django 3.2.6 on 2022-01-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0020_auto_20220104_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'permissions': (('packup_process', '合并流程'), ('dispatch_process', '分发流程'), ('approval_process', '审批权限'), ('view_submitted_process', '查看已提交课题需求'), ('view_unsubmitted_process', '查看未提交课题需求'), ('edit_process1', '编辑课题1'), ('delete_process1', '删除课题1'), ('submit_process1', '提交课题1'), ('edit_process2', '编辑课题2'), ('dispatch_process1', '分发课题'), ('delete_process2', '删除课题2'), ('edit_process3', '编辑课题3'), ('delete_process3', '删除课题3'), ('submit_process2', '提交课题2'), ('edit_process4', '编辑课题4'), ('add_process2', '创建课题2'), ('re_dispatch_process', '指派课题'), ('delete_process4', '删除课题4'), ('edit_process5', '编辑课题5'), ('submit_process3', '提交课题3'), ('deny_process', '驳回课题'), ('withdraw_process', '撤回课题'), ('manage_process', '管理课题'))},
        ),
    ]
