# Generated by Django 3.2.6 on 2021-10-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0021_auto_20211015_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={'permissions': (('patch_requirement', 'can patch requirement'),)},
        ),
    ]
