# Generated by Django 3.2.6 on 2021-10-18 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0022_alter_projectrequirement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
