# Generated by Django 3.2.6 on 2022-01-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0022_alter_process_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimplement',
            name='project_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implements', to='ApprovalSystemOCT.projectimplementtitle'),
        ),
    ]
