# Generated by Django 3.2.6 on 2021-10-18 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0023_process_creat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_creat_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
