# Generated by Django 3.2.6 on 2021-10-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0024_auto_20211018_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('1', 'processing'), ('2', 'not start'), ('3', 'finished'), ('4', 'abort'), ('5', 'pending')], default='1', max_length=5),
        ),
    ]
