# Generated by Django 3.2.6 on 2022-02-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0025_auto_20220207_1434'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='implementmaintask',
            constraint=models.UniqueConstraint(fields=('base', 'issue'), name='unique_main_task'),
        ),
        migrations.AddConstraint(
            model_name='implementsubtask',
            constraint=models.UniqueConstraint(fields=('base', 'project_task'), name='unique_sub_task'),
        ),
    ]
