# Generated by Django 3.2.6 on 2022-02-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0026_auto_20220207_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projectSystem/2022/2/', verbose_name='上传文件')),
                ('project_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.projectrequirement')),
            ],
        ),
    ]
