# Generated by Django 3.2.6 on 2022-02-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0028_auto_20220223_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('founding_usage', models.CharField(max_length=255, verbose_name='经费试用情况')),
                ('project_closure_info', models.TextField(verbose_name='课题完成情况')),
                ('status', models.CharField(default='0', help_text='0：未提交； 1：已提交；2：已通过；3：已驳回；', max_length=10, verbose_name='状态')),
                ('project_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.projectrequirement')),
            ],
        ),
    ]
