# Generated by Django 3.2.6 on 2021-10-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0029_projectimplement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimplement',
            name='department',
        ),
        migrations.RemoveField(
            model_name='projectimplement',
            name='progress_season',
        ),
        migrations.RemoveField(
            model_name='projectimplement',
            name='progress_year',
        ),
        migrations.RemoveField(
            model_name='projectimplement',
            name='sponsor',
        ),
        migrations.CreateModel(
            name='ProjectImplementTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人')),
                ('department', models.CharField(max_length=255, verbose_name='责任单位/部门')),
                ('progress_year', models.CharField(max_length=20, verbose_name='编报年')),
                ('progress_season', models.CharField(max_length=20, verbose_name='编报季度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.projectrequirement')),
            ],
        ),
        migrations.AlterField(
            model_name='projectimplement',
            name='project_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApprovalSystemOCT.projectimplementtitle'),
        ),
    ]
