# Generated by Django 3.2.6 on 2022-02-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0029_projectclosure'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectclosure',
            constraint=models.UniqueConstraint(fields=('project_base',), name='unique_project_name'),
        ),
    ]
