# Generated by Django 3.2.6 on 2021-11-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0032_alter_processtype_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='next',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='prep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
