# Generated by Django 3.2.6 on 2022-02-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0032_requirementfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclosure',
            name='project_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_base', to='ApprovalSystemOCT.projectrequirement'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='project_type',
            field=models.CharField(choices=[('0', '未选择'), ('1', '前瞻战略研究'), ('2', '产品管理研究'), ('3', '产品创新研究')], default='0', help_text='0.未选择,1.创新前瞻性研究；2.产品标准化研究，3.产品创新研究', max_length=25, verbose_name='课题类型'),
        ),
    ]
