# Generated by Django 3.2.6 on 2021-11-08 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0033_auto_20211101_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_co_worker',
            field=models.ManyToManyField(related_name='co_worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
