# Generated by Django 3.2.6 on 2021-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0034_task_task_co_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='conjunction',
            field=models.JSONField(default=dict, verbose_name='关联'),
        ),
    ]
