# Generated by Django 3.2.6 on 2022-02-26 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0034_projectclosure_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclosure',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectclosure',
            name='request_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectclosure',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
