# Generated by Django 3.2.6 on 2022-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0035_auto_20220226_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementfiles',
            name='file',
            field=models.FileField(upload_to='projectSystem/2022/3/', verbose_name='上传文件'),
        ),
        migrations.AlterField(
            model_name='requirementoutcomes',
            name='file',
            field=models.FileField(upload_to='projectSystem/2022/3/', verbose_name='上传文件'),
        ),
    ]
