# Generated by Django 3.2.6 on 2021-11-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0035_process_conjunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='next',
            field=models.JSONField(default=dict, verbose_name='后继'),
        ),
        migrations.AlterField(
            model_name='process',
            name='prep',
            field=models.JSONField(default=dict, verbose_name='前序'),
        ),
    ]
