# Generated by Django 3.2.6 on 2022-03-17 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0036_auto_20220315_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallog',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectclosure',
            name='status',
            field=models.CharField(default='0', help_text='0：未提交； 1：已提交；2：已通过；3：已驳回；4：撤回', max_length=10, verbose_name='状态'),
        ),
    ]
