# Generated by Django 3.2.6 on 2021-11-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0036_auto_20211109_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='prep',
            new_name='prev',
        ),
    ]
