# Generated by Django 3.2.6 on 2021-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0039_alter_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='read_only',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
