# Generated by Django 3.2.6 on 2021-11-15 14:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0040_process_read_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_project_name', models.CharField(max_length=500, verbose_name='课题名称')),
                ('fin_project_type', models.CharField(max_length=255, verbose_name='课题类型')),
                ('fin_departments', models.JSONField(null=True, verbose_name='课题组成单位')),
                ('fin_groups', models.CharField(max_length=500, verbose_name='课题参与团队')),
                ('fin_start_time', models.DateTimeField(default=datetime.datetime(2021, 11, 15, 14, 8, 27, 695683), verbose_name='开始时间')),
                ('fin_end_time', models.DateTimeField(default=datetime.datetime(2021, 11, 15, 14, 8, 27, 695683), verbose_name='结束时间')),
                ('fin_funding_status', models.CharField(max_length=500, verbose_name='经费使用情况')),
                ('fin_project_achievement', models.CharField(max_length=500, verbose_name='课题结题成果')),
                ('fin_project_situation', models.TextField(help_text='包括研究的背景、过程、结果及问题等', verbose_name='课题完成情况')),
                ('fin_pre_audit', models.TextField(verbose_name='预检查情况')),
                ('fin_project_sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='课题负责人')),
            ],
        ),
    ]
