# Generated by Django 3.2.6 on 2021-11-15 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0041_finalize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalize',
            name='fin_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='finalize',
            name='fin_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
