# Generated by Django 3.2.6 on 2021-11-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0042_auto_20211115_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequirement',
            name='project_approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='立项时间'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project_head_master',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='分管院长'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project_outsourcing_companies',
            field=models.JSONField(blank=True, null=True, verbose_name='外部合作单位'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project_outsourcing_info',
            field=models.JSONField(blank=True, null=True, verbose_name='外部合作内容'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project_sponsor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='负责人'),
        ),
    ]
