# Generated by Django 3.2.6 on 2021-11-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0043_auto_20211117_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='project_type',
            field=models.CharField(choices=[('0', '未选择'), ('1', '前瞻战略研究'), ('2', '产品标准化研究'), ('3', '产品创新研究')], default='0', help_text='0.未选择,1.创新前瞻性研究；2.产品标准化研究，3.产品创新研究', max_length=25, verbose_name='课题类型'),
        ),
    ]
