# Generated by Django 3.2.6 on 2021-11-22 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0044_auto_20211119_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('task_type', models.CharField(max_length=255, verbose_name='任务类型')),
                ('task_init_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='任务开始时间')),
                ('task_duration', models.DurationField(help_text='流程持续天数', null=True, verbose_name='持续时长')),
                ('task_end_time', models.DateTimeField(blank=True, null=True, verbose_name='任务结束时间')),
                ('status', models.CharField(choices=[('1', 'processing'), ('2', 'not start'), ('3', 'finished'), ('4', 'abort'), ('5', 'pending')], default='1', max_length=5)),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_executor', models.ManyToManyField(related_name='task_executors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
