# Generated by Django 3.2.6 on 2021-11-22 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0045_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ApprovalSystemOCT.tasktype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='task_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
