# Generated by Django 3.2.6 on 2021-11-22 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApprovalSystemOCT', '0047_auto_20211122_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_co_worker',
            field=models.ManyToManyField(related_name='process_co_worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
