# Generated by Django 3.2.6 on 2021-11-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystemOCT', '0048_process_process_co_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='研究方向')),
                ('description', models.TextField(verbose_name='描述')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectrequirement',
            name='project_research_direction',
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project_research_direction',
            field=models.ManyToManyField(to='ApprovalSystemOCT.ProjectDirection'),
        ),
    ]
